import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import librosa
import librosa.display

st.set_page_config(page_title="Odissi Architect", layout="wide")
st.title("🎻 Odissi Architect: Dashboard")

# --- FILE UPLOADERS ---
st.sidebar.header("1. Upload Data")
file_main = st.sidebar.file_uploader("Upload _analysis.csv", type=["csv"], key="main")
file_spec = st.sidebar.file_uploader("Upload _spectral.csv (Optional)", type=["csv"], key="spec")

if file_main:
    df = pd.read_csv(file_main)
    tonic = df['tonic'].iloc[0]
    
    # Clean Pitch
    df = df[df['pitch'] > 50]
    df['cents'] = 1200 * np.log2(df['pitch'] / tonic)
    
    # --- TAB 1: MELODY ---
    tab1, tab2, tab3 = st.tabs(["Melody", "Structure (Motifs)", "Timbre (Chest Voice)"])
    
    with tab1:
        st.subheader(f"Melodic Contour (Sa = {tonic:.1f} Hz)")
        fig, ax = plt.subplots(figsize=(10, 4))
        ax.plot(df['time'], df['cents'], color='#d9534f')
        ax.axhline(0, color='black', linestyle='--', label='Sa')
        ax.axhline(702, color='gray', linestyle=':', label='Pa')
        ax.set_ylabel("Cents"); ax.set_xlabel("Time (s)")
        st.pyplot(fig)

    # --- TAB 2: STRUCTURE (CRASH FIX) ---
    with tab2:
        st.subheader("Motif Repetition Matrix")
        
        # CRASH FIX: Downsample!
        # Instead of analyzing 44100 points, we analyze 1 point every 0.5 seconds.
        # This reduces memory usage by 90%.
        hop_length = 20  # Take every 20th point
        pitch_downsampled = df['cents'].values[::hop_length]
        time_downsampled = df['time'].values[::hop_length]
        
        if len(pitch_downsampled) > 50:
            # Smooth the curve to find 'shapes' not just exact notes
            from scipy.ndimage import gaussian_filter1d
            pitch_smooth = gaussian_filter1d(pitch_downsampled, sigma=2)
            
            # Calculate Matrix
            recurrence = librosa.segment.recurrence_matrix(
                pitch_smooth.reshape(1, -1), 
                mode='affinity', 
                width=3, 
                metric='euclidean'
            )
            
            fig2, ax2 = plt.subplots(figsize=(8, 8))
            librosa.display.specshow(recurrence, x_axis='s', y_axis='s', 
                                     x_coords=time_downsampled, y_coords=time_downsampled, 
                                     ax=ax2, cmap='Greys')
            ax2.set_title("Dark Spots = Repeating Phrases")
            st.pyplot(fig2)
        else:
            st.warning("Recording too short for structure analysis.")

    # --- TAB 3: TIMBRE (REQUIRES 2ND FILE) ---
    with tab3:
        if file_spec:
            spec_df = pd.read_csv(file_spec)
            st.subheader("Spectral Fingerprint")
            fig3, ax3 = plt.subplots(figsize=(10, 4))
            ax3.semilogx(spec_df['freq'], spec_df['db'], color='purple')
            
            # Zones
            ax3.axvspan(200, 800, color='yellow', alpha=0.2, label="Chest Voice")
            ax3.axvspan(2000, 5000, color='green', alpha=0.1, label="Head Voice")
            ax3.legend()
            st.pyplot(fig3)
        else:
            st.info("⚠️ To see Timbre, please upload the `_spectral.csv` file generated by Factory v5.")
